#!/usr/bin/env node

const program = require('commander');
const path = require('path');

const baseDir = path.resolve(__dirname, '..');
const srcDir = path.resolve(baseDir, 'web');

const gm = require('gm');

program.parse(process.argv);

function createThumbnail() {
  const img = gm(program.args[0]);

  img.resize(40);
  img.noProfile();
  img.write('test.jpg', (err) => {
    if (err) {
      console.log(err)
    }
  });
}

createThumbnail();
